import { type Edge, type Node } from 'ng-diagram';
import { type TreeEdgeData, type TreeNodeData } from './interfaces';

export const diagramModel: {
  nodes: Node<TreeNodeData>[];
  edges: Edge<TreeEdgeData>[];
} = {
  nodes: [
    {
      id: 'thomas-walther',
      position: { x: 0, y: 0 },
      data: { label: 'Thomas Walther', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'sarah-chen',
      position: { x: 0, y: 0 },
      data: { label: 'Sarah Chen', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'marcus-thompson',
      position: { x: 0, y: 0 },
      data: { label: 'Marcus Thompson', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'james-rodriguez',
      position: { x: 0, y: 0 },
      data: { label: 'James Rodriguez', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'emily-watson',
      position: { x: 0, y: 0 },
      data: { label: 'Emily Watson', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'michael-davis',
      position: { x: 0, y: 0 },
      data: { label: 'Michael Davis' },
      type: 'treeNode',
    },
    {
      id: 'diana-patel',
      position: { x: 0, y: 0 },
      data: { label: 'Diana Patel', hasChildren: true },
      type: 'treeNode',
    },
    {
      id: 'carlos-martinez',
      position: { x: 0, y: 0 },
      data: { label: 'Carlos Martinez' },
      type: 'treeNode',
    },
    {
      id: 'thomas-green',
      position: { x: 0, y: 0 },
      data: { label: 'Thomas Green' },
      type: 'treeNode',
    },
    {
      id: 'patricia-moore',
      position: { x: 0, y: 0 },
      data: { label: 'Patricia Moore' },
      type: 'treeNode',
    },
    {
      id: 'robert-kim',
      position: { x: 0, y: 0 },
      data: { label: 'Robert Kim' },
      type: 'treeNode',
    },
  ],
  edges: [
    {
      id: 'e-tw-sc',
      source: 'thomas-walther',
      sourcePort: 'port-bottom',
      target: 'sarah-chen',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-tw-mt',
      source: 'thomas-walther',
      sourcePort: 'port-bottom',
      target: 'marcus-thompson',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-tw-jr',
      source: 'thomas-walther',
      sourcePort: 'port-bottom',
      target: 'james-rodriguez',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-tw-ew',
      source: 'thomas-walther',
      sourcePort: 'port-bottom',
      target: 'emily-watson',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-sc-md',
      source: 'sarah-chen',
      sourcePort: 'port-bottom',
      target: 'michael-davis',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-sc-dp',
      source: 'sarah-chen',
      sourcePort: 'port-bottom',
      target: 'diana-patel',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-mt-cm',
      source: 'marcus-thompson',
      sourcePort: 'port-bottom',
      target: 'carlos-martinez',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-jr-tg',
      source: 'james-rodriguez',
      sourcePort: 'port-bottom',
      target: 'thomas-green',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-ew-pm',
      source: 'emily-watson',
      sourcePort: 'port-bottom',
      target: 'patricia-moore',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
    {
      id: 'e-dp-rk',
      source: 'diana-patel',
      sourcePort: 'port-bottom',
      target: 'robert-kim',
      targetPort: 'port-top',
      type: 'treeEdge',
      data: {},
    },
  ],
};
